ax, ay = input().split()
ax, ay = int(ax), int(ay)
bx, by = input().split()
bx, by = int(bx), int(by)
cx, cy = input().split()
cx, cy = int(cx), int(cy)
x = (ax if bx == cx else bx if ax == cx else cx)
y = (ay if by == cy else by if ay == cy else cy)
print(x, y)
